CREATE TABLE [blt].[Client]
(
	[ClientId] UNIQUEIDENTIFIER NOT NULL,
	[DomainId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(1024) NOT NULL,
	[SecretKey] UNIQUEIDENTIFIER NOT NULL,
	[SecretSalt] BINARY(16) NOT NULL,
	[IsActive] BIT CONSTRAINT [DF_Client_IsActive] DEFAULT (1) NOT NULL,
	[CreateTimestamp] DATETIME2(4) CONSTRAINT [DF_Client_CreateTimestamp] DEFAULT(SYSUTCDATETIME()) NOT NULL,
	[UpdateTimestamp] DATETIME2(4) CONSTRAINT [DF_Client_UpdateTimestamp] DEFAULT(SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_Client] PRIMARY KEY NONCLUSTERED ([ClientId])
)

GO

CREATE CLUSTERED INDEX [IX_Client_DomainId] ON [blt].[Client] ([DomainId])
