CREATE TABLE [bla].[Account]
(
	[AccountGuid] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[Name] NVARCHAR(2000) NOT NULL,
	[CreateTimestamp] DATETIME2(4) DEFAULT(SYSUTCDATETIME()) NOT NULL,
	[UpdateTimestamp] DATETIME2(4) DEFAULT(SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED ([AccountGuid])
)
