CREATE TABLE [blc].[Item]
(
	[ItemId] BIGINT IDENTITY(1,1) NOT NULL,
	[Code] VARCHAR(256) NOT NULL,
	[Data] NVARCHAR(MAX) NOT NULL,
	[CreateTimestamp] DATETIME2(4) DEFAULT(SYSUTCDATETIME()) NOT NULL,
	[UpdateTimestamp] DATETIME2(4) DEFAULT(SYSUTCDATETIME()) NOT NULL,
	CONSTRAiNT [PK_Item] PRIMARY KEY CLUSTERED ([ItemId])
)
